In [2]:
import pandas as pd
data={
    'product':['laptop','Smartphone','Monitor','Headphone','Mouse'],
    'Price':[200000,180000,15000,32000,5000],
    'Sales':[150000,120000,10000,12000,1000],
    'profit':[50000,20000,5000,5000,2000]
}
df=pd.DataFrame(data)
print(df)

      product   Price   Sales  profit
0      laptop  200000  150000   50000
1  Smartphone  180000  120000   20000
2     Monitor   15000   10000    5000
3   Headphone   32000   12000    5000
4       Mouse    5000    1000    2000

In [9]:
print(df.shape)

(5, 4)

In [12]:
df.head()

      product   Price   Sales  profit
0      laptop  200000  150000   50000
1  Smartphone  180000  120000   20000
2     Monitor   15000   10000    5000
3   Headphone   32000   12000    5000
4       Mouse    5000    1000    2000

In [51]:
#View first few rows
df.head(2)

#view random smples
import random as rn
df.sample(3,axis=0)
df.loc[0:2,['Price','Sales']]

#ranomly fractions ...
df.sample(frac=0.5)

#display sample basd on condition
df[(df.Price>10000)&(df.Sales>100000)]

      product   Price   Sales  profit
0      laptop  200000  150000   50000
1  Smartphone  180000  120000   20000

In [58]:
#sort the data in ascending order wrt particular column
df.sort_values('Price',ascending=False)

      product   Price   Sales  profit
0      laptop  200000  150000   50000
1  Smartphone  180000  120000   20000
3   Headphone   32000   12000    5000
2     Monitor   15000   10000    5000
4       Mouse    5000    1000    2000

In [106]:
#Build list of random number .convert it dictionary 
# and then to a dtaframe
import random 
sh=random.choices(range(1,11),k=100)
sts=random.choices(range(1,11),k=100)
print(sh)
print(sts)

dic={
    'Studying':sh,
    'Testscore':sts
}
df=pd.DataFrame(dic)
df.head()

#display the datatype of studyhour
print(df['Studying'].dtype)

print(df['Studying'].dtype)
#display the missing values in the data
df.isnull().sum()

[3, 10, 6, 7, 2, 9, 4, 6, 2, 7, 5, 1, 6, 6, 3, 4, 2, 3, 4, 6, 5, 7, 10, 6, 2, 10, 10, 1, 10, 1, 5, 6, 8, 7, 9, 4, 1, 9, 10, 4, 2, 6, 3, 8, 10, 8, 8, 3, 7, 7, 10, 10, 10, 5, 1, 2, 5, 5, 8, 3, 6, 1, 10, 6, 6, 2, 5, 3, 5, 5, 9, 5, 8, 7, 2, 7, 3, 6, 8, 1, 2, 5, 6, 10, 9, 3, 9, 6, 7, 8, 1, 5, 8, 1, 8, 4, 10, 4, 4, 4]
[9, 2, 7, 6, 1, 9, 1, 9, 3, 3, 3, 7, 10, 1, 10, 2, 10, 8, 3, 2, 9, 4, 2, 4, 2, 3, 9, 10, 10, 6, 3, 2, 5, 6, 6, 3, 9, 2, 3, 3, 9, 6, 5, 1, 4, 5, 7, 8, 3, 3, 8, 3, 10, 3, 5, 7, 5, 8, 10, 7, 7, 4, 5, 5, 4, 7, 5, 10, 7, 7, 1, 4, 10, 4, 8, 8, 4, 1, 8, 6, 3, 1, 10, 4, 5, 4, 1, 2, 8, 10, 3, 6, 10, 7, 6, 2, 9, 10, 9, 2]
int64
int64

Studying     0
Testscore    0
dtype: int64

In [85]:
l=random.choices(range(1,101),k=4)
print(l)
df.loc[l,'Testscore']=None
print(df.isnull().sum())

[17, 14, 6, 3]
Studying     0
Testscore    4
dtype: int64

In [87]:
print(df[df.isnull().any(axis=1)])

    Studying  Testscore
3          4        NaN
6          2        NaN
14         4        NaN
17         6        NaN

In [94]:
#from another dataframe wthout considering these missing value and compare both size
df2=df.dropna()
df2

    Studying  Testscore
0          3        7.0
1          4        5.0
2          1        3.0
4          2        1.0
5         10        8.0
..       ...        ...
95         3        4.0
96        10        8.0
97         3        5.0
98         1        3.0
99        10        5.0

[96 rows x 2 columns]

In [107]:
#find out unique or distinct values in a particular coulumn 
# coulumn studyhour
print(df['Studying'].unique())
# particular column number and its freequency
print(df['Studying'].value_counts())

[ 3 10  6  7  2  9  4  5  1  8]
6     14
10    13
5     12
8     10
3      9
7      9
2      9
4      9
1      9
9      6
Name: Studying, dtype: int64